from flask import Flask, render_template, request, redirect, url_for, jsonify, send_file
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from modules.auth import get_user
from modules.monitor import get_network_data
from modules.detector import detect_threats
from modules.ai_helper import explain_alert

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

app = Flask(__name__)
app.secret_key = "supersecretkey"

login_manager = LoginManager()
login_manager.init_app(app)

# 🔐 USER LOADER
@login_manager.user_loader
def load_user(user_id):
    return get_user(user_id)

# 🔐 LOGIN
@app.route("/", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        user = get_user(request.form["username"])
        if user and user.password == request.form["password"]:
            login_user(user)
            return redirect(url_for("dashboard"))
    return render_template("login.html")

# 📊 DASHBOARD
@app.route("/dashboard")
@login_required
def dashboard():
    return render_template("dashboard.html", role=current_user.role)

# 🚨 ALERTS
@app.route("/alerts")
@login_required
def alerts():
    return render_template("alerts.html", role=current_user.role)

# 👑 ADMIN
@app.route("/admin")
@login_required
def admin():
    if current_user.role != "admin":
        return "Access Denied"
    return render_template("admin.html", role=current_user.role)

# 🔁 REAL-TIME DATA
@app.route("/api/data")
@login_required
def api_data():
    data = get_network_data()
    alerts = detect_threats(data)
    return jsonify({"connections": data, "alerts": alerts})

# 🤖 AI EXPLAIN
@app.route("/explain", methods=["POST"])
@login_required
def explain():
    return explain_alert(request.form["alert"])

# 📥 PDF REPORT (FIXED)
@app.route("/download_report")
@login_required
def download_report():
    doc = SimpleDocTemplate("report.pdf")
    styles = getSampleStyleSheet()

    data = get_network_data()
    alerts = detect_threats(data)

    content = []

    content.append(Paragraph("Cyber Security Report", styles['Title']))
    content.append(Spacer(1, 10))

    if not alerts:
        content.append(Paragraph("No threats detected.", styles['Normal']))
    else:
        for a in alerts:
            text = f"[{a['severity']}] {a['message']}"
            content.append(Paragraph(text, styles['Normal']))
            content.append(Spacer(1, 5))

    content.append(Spacer(1, 15))
    content.append(Paragraph("Generated by Cyber AI Monitor", styles['Italic']))

    doc.build(content)

    return send_file("report.pdf", as_attachment=True)

# 🔓 LOGOUT
@app.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect("/")

if __name__ == "__main__":
    app.run(debug=True)
